version: '3.8'

services:
  web:
    build: .
    # Мапим порт: на твоем компе 8000 -> внутри контейнера 8000
    ports:
      - "8000:8000"
    # volumes позволяют менять код на компе и видеть изменения в контейнере без перезагрузки
    volumes:
      - .:/app
    # Если будет файл .env, докер подтянет переменные оттуда
    env_file:
      - .env
    # Команда запуска (дублируем на всякий случай)
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Задел на будущее (база данных)
  # db:
  #   image: postgres:15
  #   ... (раскомментируем, когда дойдем до БД)