services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Мапим всё в /app, так как WORKDIR в Dockerfile — /app
    env_file:
      - .env
    # Правильный путь к приложению: папка src -> файл main -> объект app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload